### ISSUE TITLE
Intern Status Updates on Accelerated Monte Carlo

### ISSUE THREAD

**Issue by CaidanS** [actuarialopensource/Computational-Actuarial-Science#7]
# Task Overview

While we can calculate the actuarial expected values of a portfolio of annuities, it is impossible to generate a closed form solution to model the distribution. In order to get around this, we can generate an empirical distribution via a Monte Carlo simulation. 

However, running such simulations on large portfolios is computationally intensive, and can be prohibitively slow. By using the JAX library, we can vectorize our code to take advantage of hardware acceleration (GPUs/TPUs) by running parallel simulations and generating our distribution from the results. 

I'll try to use this issue as a log of what I am working on and how things are going!

# Progress
- [x] Get a handle on annuities mechanics
- [x] Write up naive implementation of annuity MC simulation
- [x] Read through the JAX documentation
- [ ] Adapt current vectorized time step model for annuities
- [ ] Look into pmap/using multiple processing units to further accelerate
- [ ] Look into calculating greeks in addition to values

# Resources I've Found Helpful

On variable annuities but very well written and good section on metamodeling/computation as well as calculating greeks. 
[Gan and Valdez 2017](https://www.degruyter.com/document/doi/10.1515/demo-2017-0021/html?lang=en)
Good overview of modeling techniques
[Dardis 2016](https://www.soa.org/globalassets/assets/Library/Newsletters/The-Modeling-Platform/2016/april/mp-2016-iss3-dardis.pdf)

**Comment by MatthewCaseres** [comment]
I think that `rho` is the greek that applies most to simple insurance products. I am like 99.9% sure nobody has calculated `rho` for an annuity portfolio.

It sort of depends on what journal you'd want to publish in. If you want to publish in [parallel computing](https://www.elsevier.com/journals/parallel-computing/0167-8191/guide-for-authors) then it is more analysis of algorithms and about GPU acceleration. If you want to publish in [computational finance](https://www.ssrn.com/index.cfm/en/journal-of-computational-finance/) then maybe the autodiff is the central focus.

So life insurance (10 year term, 20 year term, whole life) and annuities are actually natural hedges to each other in terms of longevity risk. Low mortality increases life insurance profits but decreases annuity profits. Maybe there is a hedge on interest rates in there somehow too. I wonder if the autodiff allows for us to optimize portfolio/investment options to zero out the gradient with respect to mortality rates. What portfolio minimizes risk due to age 65 mortality? Can we construct the portfolio using gradient descent?

**Comment by CaidanS** [comment]
Sounds good, I think I'll look more towards [computational finance](https://www.ssrn.com/index.cfm/en/journal-of-computational-finance/)/optimization. Interest rates are unfortunately pretty topical right now!
